# Generated by Django 2.2 on 2020-10-19 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='isyeri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isyeriAdi', models.CharField(max_length=130, verbose_name='İşyeri Adı')),
                ('isyeriBolge', models.CharField(blank=True, max_length=30, null=True, verbose_name='İşyeri Bölgesi')),
                ('isyeriSicil', models.CharField(blank=True, max_length=100, null=True, verbose_name='İşyeri Sicil No')),
                ('isyeriEklenmeZamani', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
