# Generated by Django 2.2 on 2020-11-05 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eslestirme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eslestirme',
            name='yetkiliOsgbUzmani_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Yetki_osgb_uzm_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eslestirme',
            name='yetkiliOsgbUzmani_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Yetki_osgb_uzm_4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eslestirme',
            name='yetkiliOsgbUzmani_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Yetki_osgb_uzm_5', to=settings.AUTH_USER_MODEL),
        ),
    ]
