# Generated by Django 2.2 on 2020-11-09 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eslestirme', '0003_auto_20201109_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='eslestirme',
            name='Olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OlusturanYetkilendirme', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Personel'),
        ),
    ]
