# Generated by Django 2.2 on 2020-11-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eslestirme', '0004_eslestirme_olusturan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eslestirme',
            name='Olusturan',
        ),
    ]
