# Generated by Django 2.2 on 2020-10-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvrakAdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.PositiveIntegerField(verbose_name='Sıra No')),
                ('evrak_adi', models.CharField(max_length=300, verbose_name='Evrak Adı')),
                ('az_tehlike', models.PositiveIntegerField(verbose_name='Az Tehlikeli için Süre(Ay)')),
                ('tehlike', models.PositiveIntegerField(verbose_name='Tehlikeli için Süre(Ay)')),
                ('cok_tehlike', models.PositiveIntegerField(verbose_name='Çok Tehlikeli için Süre(Ay)')),
            ],
        ),
    ]
