# Generated by Django 2.2 on 2020-10-22 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosyayukle', '0004_auto_20201022_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosyaOnay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField(blank=True, default='Açıklama Henüz Yok.!', null=True, verbose_name='Açıklama')),
                ('dosya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosya', to='dosyayukle.DosyaYukle')),
                ('evrakad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evrakad', to='dosyayukle.DosyaYukle')),
                ('isyeriAd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isyeriAd', to='dosyayukle.DosyaYukle')),
                ('olusturmaTarihi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olusturmaTarihi', to='dosyayukle.DosyaYukle')),
                ('projead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projead', to='dosyayukle.DosyaYukle')),
                ('uzman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uzman', to='dosyayukle.DosyaYukle')),
            ],
        ),
    ]
