# Generated by Django 2.2 on 2020-10-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyaonay', '0002_auto_20201030_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosyaonay',
            name='aciklama',
            field=models.TextField(blank=True, default='Açıklama Henüz Yok.!', max_length=340, null=True, verbose_name='Açıklama'),
        ),
    ]
