# Generated by Django 2.2 on 2020-10-19 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('isyeriekle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calisilanFirmalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmaAd', models.CharField(max_length=200, verbose_name='Çalışılacak Firma Adı')),
                ('SicilNumarasi', models.CharField(max_length=110, verbose_name="Çalışılacak Firma'nın Sicil No")),
                ('tehlikeSinif', models.CharField(choices=[('Az Tehlikeli', 'Az Tehlikeli'), ('Tehlikeli', 'Tehlikeli'), ('Çok Tehlikeli', 'Çok Tehlikeli')], max_length=60, verbose_name='Tehlike Sınıfı')),
                ('isyeriCalisanSayisi', models.PositiveIntegerField(verbose_name='Çalışan sayısı')),
                ('isyeriBolge', models.CharField(max_length=40, verbose_name='Bölge')),
                ('isyeri_ilcesi', models.CharField(max_length=50, verbose_name='İlçe')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Yetkili Ad Soyad')),
                ('telefon', models.CharField(max_length=100, verbose_name='Yetkili Telefonu')),
                ('e_posta', models.CharField(max_length=200, verbose_name='Yetkili E - Posta')),
                ('kayitTarih', models.DateField(default=datetime.date.today)),
                ('Sirket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isyeriekle.isyeri')),
            ],
        ),
    ]
