# Generated by Django 2.2 on 2020-11-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calisilanFirma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calisilanfirmalar',
            name='SicilNumarasi',
            field=models.CharField(max_length=110, unique=True, verbose_name="Çalışılacak Firma'nın Sicil No"),
        ),
    ]
