# Generated by Django 2.2 on 2020-10-19 13:31

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evrakAdi', '0001_initial'),
        ('isyeriekle', '0001_initial'),
        ('calisilanFirma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DosyaYukle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosyaYuklenmeTarihi', models.DateField(default=datetime.date.today, verbose_name='Dosya Hazırlama Tarihi')),
                ('Dosya', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('evrakAdi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evrakAdi', to='evrakAdi.EvrakAdi', verbose_name='Evrak Adı')),
                ('isyeri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isyerim', to='isyeriekle.isyeri', verbose_name='İş Yeri Adı')),
                ('osgbUzmanAdi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osgbUzmanAdi', to=settings.AUTH_USER_MODEL, verbose_name='Yetkili OSGB Uzmanı')),
                ('projeAdi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projeAdi', to='calisilanFirma.calisilanFirmalar', verbose_name='Proje Adı')),
            ],
        ),
    ]
