# Generated by Django 2.2 on 2020-10-20 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyayukle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosyayukle',
            name='Dosya',
            field=models.FileField(blank=True, default='DOSYA YOK', null=True, upload_to='documents/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
