# Generated by Django 2.2 on 2020-10-22 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyayukle', '0002_auto_20201020_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosyayukle',
            name='Dosya',
            field=models.FileField(blank=True, default='DOSYA YOK', null=True, upload_to='documents/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', ''])]),
        ),
    ]
