# Generated by Django 2.2 on 2020-10-26 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyayukle', '0004_auto_20201022_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosyayukle',
            name='onay',
            field=models.BooleanField(default=False, verbose_name='Dosya Onay'),
        ),
        migrations.AddField(
            model_name='dosyayukle',
            name='red',
            field=models.BooleanField(default=False, verbose_name='Dosya Ret '),
        ),
        migrations.AddField(
            model_name='dosyayukle',
            name='tarih',
            field=models.DateField(default=datetime.date.today, verbose_name='Dosya Onay Tarihi'),
        ),
    ]
