# Generated by Django 2.2 on 2020-10-26 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyayukle', '0005_auto_20201026_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosyayukle',
            name='Dosya',
            field=models.FileField(default=None, upload_to='documents/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
