# Generated by Django 2.2 on 2020-10-30 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyayukle', '0009_dosyayukle_olusturan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosyayukle',
            name='Aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosyayukle',
            name='dosyaGecerlilikTarihi',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Dosya Geçerlilik Tarihi'),
        ),
    ]
