# Generated by Django 2.2 on 2020-11-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosyayukle', '0013_auto_20201105_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosyayukle',
            name='osgbUzmanAdi',
        ),
    ]
