# Generated by Django 2.2 on 2020-11-09 08:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosyayukle', '0017_auto_20201109_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosyayukle',
            name='Olusturan',
            field=models.ForeignKey(default=datetime.date, on_delete=django.db.models.deletion.CASCADE, related_name='Olusturan', to=settings.AUTH_USER_MODEL, verbose_name='Görevli Personel'),
            preserve_default=False,
        ),
    ]
