# Generated by Django 2.2 on 2020-11-09 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyayukle', '0018_auto_20201109_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosyayukle',
            name='GecerlilikTarihi',
            field=models.DateField(default=datetime.date.today, verbose_name='Dosya Geçerlilik Tarihi'),
        ),
    ]
